package org.user.app.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
public class Product {

    /**
     * The primary key of the entity. 
     * It is automatically generated by the database.
     * 
     * @Id specifies that this field is the primary key of the entity.
     * @GeneratedValue with strategy = GenerationType.SEQUENCE indicates that the ID is generated using a sequence.
     * @SequenceGenerator defines the sequence used for ID generation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "product_seq")
    @SequenceGenerator(name = "product_seq", sequenceName = "product_sequence", allocationSize = 1)
    private Long id;

    /**
     * The name of the product.
     * It cannot be blank or empty.
     * 
     * @NotBlank ensures that this field must not be blank.
     * @Column specifies the column name in the database.
     */
    @NotBlank(message = "Name is mandatory")
    @Column(name="name")
    private String name;

    /**
     * The price of the product.
     * Must be greater than or equal to 1.
     * 
     * @Column specifies the column name in the database.
     * @Min ensures that the price must be at least 1.
     */
    @Column(name = "price")
    @Min(value = 1, message = "Price must be greater than or equal to 1")
    private Long price;

    /**
     * The category to which the product belongs.
     * It cannot be blank or empty.
     * 
     * @NotBlank ensures that this field must not be blank.
     * @Column specifies the column name in the database.
     */
    @NotBlank(message = "Category is mandatory")
    @Column(name="category")
    private String category;
}